### ISSUE TITLE
Swift Boot Camp Week-3 day-1

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#1]

**Comment by ghada-mhum** [comment]
غادة محمد الحميميدي

https://github.com/ghada-mhum/FirstUIAssighment

**Comment by Aljwhra** [comment]
Aljwhra Alnasser 

https://github.com/Aljwhra/HealthCare.git

**Comment by dev-striver** [comment]
Abdulrahman Alshammari

https://github.com/AbdulrahmanAlkhaled/TuawiqBootcamp.git

**Comment by seham12** [comment]
Seham Al-Marshedi

https://github.com/seham12/hm2

**Comment by SaharFaris1** [comment]
Sahar Faris
https://github.com/SaharFaris1/As2
