### ISSUE TITLE
prayer time assignment

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#10]

**Comment by dev-striver** [comment]
Abdulrahman Alshammari
https://github.com/AbdulrahmanAlkhaled/AthanApp

**Comment by seham12** [comment]
Seham ALmarshedi
https://github.com/seham12/HM-6

**Comment by NorahAlfari** [comment]
Norah Alfari 
https://github.com/NorahAlfari/PrayTime.git

**Comment by Aljwhra** [comment]
Aljwhra Alnasser 

https://github.com/Aljwhra/PrayerApp.git

**Comment by SaharFaris1** [comment]
Sahar Faris  

https://github.com/SaharFaris1/PrayTime

**Comment by ReemAlammari** [comment]
Reem Alammari
https://github.com/ReemAlammari/pryerTimes.git

**Comment by ghada-mhum** [comment]
Ghada Alhumaimidi
https://github.com/ghada-mhum/PrayerTimes

**Comment by Sara4215** [comment]
https://github.com/Sara4215/swift-labs
