### ISSUE TITLE
HigherOrderFunctions-assignment

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#11]

**Comment by ReemAlammari** [comment]
Reem Alammari
https://github.com/ReemAlammari/3method

**Comment by SaharFaris1** [comment]
https://github.com/SaharFaris1/HigherOrderFunction

Sahar Faris

**Comment by ghada-mhum** [comment]
Ghada Alhumaimidi
https://github.com/ghada-mhum/HigherOrderFunctions

**Comment by MrThree6** [comment]
Mohammad Alrajhi
https://github.com/MrThree6/HighOrderFunctions

**Comment by NorahAlfari** [comment]
Norah Alfari

**Comment by NorahAlfari** [comment]
Norah Alfari
https://github.com/NorahAlfari/HigherOrderFunctions.git

**Comment by Aljwhra** [comment]
Aljwhra  Alnasser 

https://github.com/Aljwhra/MoviesApp.git 
https://github.com/Aljwhra/ToDoDashboard.git 
https://github.com/Aljwhra/NumbersGame.git

**Comment by KhalidH9** [comment]
Khalid Alharbi

https://github.com/KhalidH9/HOFunctions.git

**Comment by dev-striver** [comment]
Abdulrahman Alshammari
https://github.com/AbdulrahmanAlkhaled/HigherOrderFunctions

**Comment by Sara4215** [comment]
https://github.com/Sara4215/swift-labs.git

**Comment by seham12** [comment]
Seham almarshedi
https://github.com/seham12/HigherOrder

**Comment by RaneemA1** [comment]
https://github.com/RaneemA1/SwiftMap.git
https://github.com/RaneemA1/SwiftFilter.git
https://github.com/RaneemA1/Filter.Map.Sort.git
Raneem Bin Dlaij

**Comment by Sara4215** [comment]
https://github.com/Sara4215/SwiftLab/tree/main/Coffe%20App/CoffeeApp/CoffeeApp.xcodeproj/project.xcworkspace
