### ISSUE TITLE
BattelOfLegeneds assignment

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#12]

**Comment by dev-striver** [comment]
Abdulrahman Alshammari
https://github.com/AbdulrahmanAlkhaled/BattelOfLegends

**Comment by NorahAlfari** [comment]
Norah Alfari 
https://github.com/NorahAlfari/BattleOfLegeneds.git

**Comment by Fahad-exe** [comment]
Fahad Matlagitu

https://github.com/Fahad-exe/BattleOfLegends

**Comment by Aljwhra** [comment]
Aljwhra Alnasser 

https://github.com/Aljwhra/BattleOfLegeneds.git

**Comment by ghada-mhum** [comment]
Ghada Alhumaimidi 

https://github.com/ghada-mhum/BattleOfLegeneds

**Comment by ReemAlammari** [comment]
Reem Alammari
https://github.com/ReemAlammari/generic.git

**Comment by RaneemA1** [comment]
https://github.com/RaneemA1/Battle.git
Raneem Bin Doaij

**Comment by Sara4215** [comment]
https://github.com/Sara4215/SwiftAssignment.git

**Comment by MrThree6** [comment]
Mohammad Alrajhi
https://github.com/MrThree6/BattleOfLegeneds

**Comment by SaharFaris1** [comment]
Sahar Faris              

https://github.com/SaharFaris1/BattelOfLegeneds

**Comment by RakanW10** [comment]
Rakan Alotibi
https://github.com/RakanW10/generic

**Comment by Sara4215** [comment]
https://github.com/Sara4215/SwiftAssignment
