### ISSUE TITLE
Week 6 Assignment 

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#13]

**Comment by dev-striver** [comment]
Abdulrahman Alshammari
https://github.com/AbdulrahmanAlkhaled/Storage.git

**Comment by KhalidH9** [comment]
Khalid Alharbi

https://github.com/KhalidH9/W6A.git

**Comment by Aljwhra** [comment]
Aljwhra Alnasser 

https://github.com/Aljwhra/Storage.git

**Comment by seham12** [comment]
Seham Almarshedi
https://github.com/seham12/-Storage

**Comment by Sara4215** [comment]
https://github.com/Sara4215/swiftassignment5/upload

**Comment by Sara4215** [comment]
https://github.com/Sara4215/swiftassignment5/tree/main/Storage%207

**Comment by RaneemA1** [comment]
https://github.com/RaneemA1/Storge.git
Raneem Bin Doaij

**Comment by ReemAlammari** [comment]
Reem Alammari
https://github.com/ReemAlammari/storage.git

**Comment by SaharFaris1** [comment]
Sahar Faris 

https://github.com/SaharFaris1/Storage

**Comment by Fahad-exe** [comment]
https://github.com/Fahad-exe/Storage

**Comment by MrThree6** [comment]
Mohammad Alrajhi
https://github.com/MrThree6/Storage

**Comment by RakanW10** [comment]
Rakan Alotibi
https://github.com/RakanW10/Storage

**Comment by NorahAlfari** [comment]
Norah Alfari 
https://github.com/NorahAlfari/Storage.git

**Comment by ghada-mhum** [comment]
Ghada Alhumaimidi
https://github.com/ghada-mhum/Storage
