### ISSUE TITLE
UIKit assignment

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#15]

**Comment by KhalidH9** [comment]
Khalid Alharbi

https://github.com/KhalidH9/W9D5HW2.git

**Comment by ReemAlammari** [comment]
Reem Alammari

**Comment by dev-striver** [comment]
Abdulrahman Alshammari
https://github.com/AbdulrahmanAlkhaled/UIKitApp

**Comment by Aljwhra** [comment]
Aljwhra Alnasser 

https://github.com/Aljwhra/X-O.git

**Comment by RaneemA1** [comment]
Raneem Bin Doaij
https://github.com/RaneemA1/Nav.git

**Comment by seham12** [comment]
Seham almarshedi
 https://github.com/seham12/UiKit

**Comment by SaharFaris1** [comment]
Sahar Faris
https://github.com/SaharFaris1/uiKit

**Comment by NorahAlfari** [comment]
Norah Alfari 
https://github.com/NorahAlfari/UIKIT4.git

**Comment by ghada-mhum** [comment]
Ghada Alhumaimidi
https://github.com/ghada-mhum/UIkitAssignment
