### ISSUE TITLE
Weekend assignment-Carplay

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#16]

**Comment by Fahad-exe** [comment]
https://github.com/Fahad-exe/AppleCarPlay

**Comment by Aljwhra** [comment]
الجوهره - رنيم 
https://github.com/Aljwhra/ParkingSpace.git

**Comment by NorahAlfari** [comment]
Norah Alfari 
https://github.com/NorahAlfari/Food.git

**Comment by dev-striver** [comment]
Abdulrahman - Mohammed
https://github.com/AbdulrahmanAlkhaled/Football

**Comment by SaharFaris1** [comment]
Sahar - Reem

https://github.com/SaharFaris1/UIKitApp

**Comment by seham12** [comment]
Seham - Ghada
https://github.com/seham12/-assignment-Carplay
