### ISSUE TITLE
Swift Boot Camp Week-3 day-2

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#2]

**Comment by KhalidH9** [comment]
Khalid Alharbi.

https://github.com/KhalidH9/HomeWork2.git

**Comment by Aljwhra** [comment]
Aljwhra Alnasser 

https://github.com/Aljwhra/HealthCare.git

**Comment by NorahAlfari** [comment]
Norah Alfari 
https://github.com/NorahAlfari/norahAssignment.git

**Comment by Mohaalsaad** [comment]
mohammed alsaad 
https://github.com/Mohaalsaad/week3-day3

**Comment by Fahad-exe** [comment]
Fahad Matlagitu

https://github.com/Fahad-exe/SecondAppExample/tree/main/ThirdExample

**Comment by ReemAlammari** [comment]
Reem Alammari
https://github.com/ReemAlammari/R

**Comment by RakanW10** [comment]
Rakan Alotibi

https://github.com/RakanW10/SwiftUI_Assignment_01

**Comment by dev-striver** [comment]
Abdulrahman Alshammari

https://github.com/AbdulrahmanAlkhaled/TuawiqBootcamp.git

**Comment by ghada-mhum** [comment]
Ghada Alhumaimidi

https://github.com/ghada-mhum/FirstUIAssighment

**Comment by seham12** [comment]
Seham Al-Marshedi
https://github.com/seham12/hm2

**Comment by SaharFaris1** [comment]
Sahar Faris
https://github.com/SaharFaris1/HC
