### ISSUE TITLE
Week 3 Assignment in Weekend 

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#7]

**Comment by KhalidH9** [comment]
Khalid Alharbi

https://github.com/KhalidH9/HW4.git

**Comment by NorahAlfari** [comment]
Norah Alfari
https://github.com/NorahAlfari/FastLoanApp.git

**Comment by ghada-mhum** [comment]
Ghada Alhumaimidi
https://github.com/ghada-mhum/WeekEndAssighment

**Comment by SaharFaris1** [comment]
Sahar Faris
https://github.com/SaharFaris1/FastLoan

**Comment by Sara4215** [comment]
https://github.com/Sara4215/swift-lab.git

**Comment by Aljwhra** [comment]
Aljwhra Alnasser 

https://github.com/Aljwhra/FastLoan.git

**Comment by dev-striver** [comment]
Abdulrahman Alshammari
https://github.com/AbdulrahmanAlkhaled/FastLoanApp.git

**Comment by seham12** [comment]
Seham almarshedi
https://github.com/seham12/Hm4

**Comment by RaneemA1** [comment]
git remote add origin https://github.com/RaneemA1/gitApp2.git

**Comment by RaneemA1** [comment]
https://github.com/RaneemA1/gitApp2.git

**Comment by RaneemA1** [comment]
Raneem Bin Doaij
 https://github.com/RaneemA1/gitApp2.git

**Comment by ReemAlammari** [comment]
Reem Alammari
https://github.com/ReemAlammari/FastLoan_project

**Comment by RakanW10** [comment]
Rakan Alotibi
https://github.com/RakanW10/SwiftLoan

**Comment by RaneemA1** [comment]
Raneem Bin Doaij
https://github.com/RaneemA1/fastLoan.git

**Comment by MrThree6** [comment]
Mohammad alrajhi

https://github.com/MrThree6/FastLoan
