### ISSUE TITLE
Assignment-MedicalApp

### ISSUE THREAD

**Issue by Mohaalsaad** [iOS-DevelopmentBootcamp-Oct-2023/Swift-Boot-Camp#8]

**Comment by seham12** [comment]
Seham Almarshedi
https://github.com/seham12/hm2

**Comment by ReemAlammari** [comment]
Reem Alammari
https://github.com/ReemAlammari/hospital

**Comment by ghada-mhum** [comment]
Ghada Alhumaimidi
https://github.com/ghada-mhum/MidicalApp

**Comment by dev-striver** [comment]
Abdulrahman Alshammari
https://github.com/AbdulrahmanAlkhaled/MedicsApp

**Comment by Aljwhra** [comment]
Aljwhra Alnasser

https://github.com/Aljwhra/HealthCare.git

**Comment by SaharFaris1** [comment]
Sahar Faris

https://github.com/SaharFaris1/MedicalApp

**Comment by RaneemA1** [comment]
Raneem Bin Doaij
https://github.com/RaneemA1/MedicalApp
